-- Data for table: EntityTypeAttribute
-- Row count: 78

INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1, 1, '2339-0', 'Glucose', 'Pt', 'mg/dL', 1, 'vitals.glucose.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.303000' AS DATETIME2), 'sa', 1, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (2, 1, '2345-7', 'Avg Glucose', 'Mean', 'mg/dL', 1, 'vitals.glucose.serum.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.303000' AS DATETIME2), 'sa', 1, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (3, 1, '59408-5', 'O2 Sat', 'Pt', '%', 1, 'vitals.oxygen_saturation.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (4, 1, '80358-0', 'AFib', 'Pt', '1', 1, 'vitals.atrial_fibrillation_detection.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.303000' AS DATETIME2), 'sa', 1, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (5, 1, '80404-7', 'HRV', 'Pt', 'ms', 1, 'vitals.heart_rate_variability.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (6, 1, '8310-5', 'Temp', 'Pt', 'Cel', 1, 'vitals.body_temperature.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.303000' AS DATETIME2), 'sa', 1, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (7, 1, '8418-4', 'RHR', 'Pt', 'bpm', 1, 'vitals.heart_rate.resting.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
-- LOINC Health Connect Code: 93832-4 (Sleep duration)
INSERT INTO [EntityTypeAttribute] ([entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active]) VALUES (1, '93832-4', 'Sleep duration', 'Pt', 'min', 2, 'sleep.duration.update', 'Y');
-- LOINC Health Connect Code: 29463-7 (Body weight)
INSERT INTO [EntityTypeAttribute] ([entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active]) VALUES (1, '29463-7', 'Body weight (kg)', 'Pt', 'kg', 2, 'body.weight.update', 'Y');
-- LOINC Health Connect Code: 55423-8 (Number of steps)
INSERT INTO [EntityTypeAttribute] ([entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active]) VALUES (1, '55423-8', 'Number of steps', 'Pt', 'count', 2, 'activity.steps.update', 'Y');
-- LOINC Health Connect Code: 55430-3 (Distance traveled)
INSERT INTO [EntityTypeAttribute] ([entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active]) VALUES (1, '55430-3', 'Distance traveled', 'Pt', 'km', 2, 'activity.distance.update', 'Y');
-- LOINC Health Connect Code: 41981-2 (Body calories burned)
INSERT INTO [EntityTypeAttribute] ([entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active]) VALUES (1, '41981-2', 'Body calories burned', 'Pt', 'kcal', 2, 'activity.calories_burned.update', 'Y');
-- LOINC Health Connect Code: 41982-0 (Percentage of body fat)
INSERT INTO [EntityTypeAttribute] ([entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active]) VALUES (1, '41982-0', 'Percentage of body fat', 'Pt', '%', 2, 'body.fat_percentage.update', 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (8, 1, '8462-4', 'DBP', 'Pt', 'mmHg', 1, 'vitals.diastolic_blood_pressure.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (9, 1, '8480-6', 'SBP', 'Pt', 'mmHg', 1, 'vitals.blood_pressure.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (10, 1, '8638-5', 'HR Min', 'Min', 'bpm', 1, 'vitals.heart_rate.minimum.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.303000' AS DATETIME2), 'sa', 1, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (11, 1, '8639-3', 'HR Max', 'Max', 'bpm', 1, 'vitals.heart_rate.maximum.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.303000' AS DATETIME2), 'sa', 1, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (12, 1, '8867-4', 'HR', 'Pt', 'bpm', 1, 'vitals.heart_rate.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (13, 1, '9279-1', 'RR', 'Pt', '{breaths}/min', 1, 'vitals.respiration_rate.update', 'Y', CAST('2026-02-07 21:01:05.547000' AS DATETIME2), CAST('2026-02-20 22:50:12.300000' AS DATETIME2), 'sa', 1, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (14, 4, 'electrical.main.voltage', 'Voltage', 'Pt', 'V', NULL, NULL, 'Y', CAST('2026-02-13 21:02:49.413000' AS DATETIME2), CAST('2026-02-21 00:01:33.340000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1014, 4, 'propulsion.port.fuelRate', 'FuleRate', 'Pt', 'm3/s', NULL, NULL, 'Y', CAST('2026-02-13 22:05:42.050000' AS DATETIME2), CAST('2026-02-21 00:01:33.353000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1031, 4, 'navigation.position', 'Position', 'Pt', '', 8, 'navigation.position', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1032, 4, 'navigation.headingMagnetic', 'Hdg Mag', 'Pt', 'rad', 8, 'navigation.headingMagnetic', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1033, 4, 'navigation.headingTrue', 'Hdg True', 'Pt', 'rad', 8, 'navigation.headingTrue', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1034, 4, 'navigation.courseOverGround', 'COG', 'Pt', 'rad', 8, 'navigation.courseOverGround', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1035, 4, 'navigation.speedOverGround', 'SOG', 'Pt', 'm/s', 8, 'navigation.speedOverGround', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1036, 4, 'navigation.speedThroughWater', 'STW', 'Pt', '', 8, 'navigation.speedThroughWater', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1037, 4, 'environment.wind.speedApparent', 'Wind Speed', 'Pt', 'm/s', 8, 'environment.wind.speedApparent', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1038, 4, 'environment.wind.directionApparent', 'Wind Dir', 'Pt', 'rad', 8, 'environment.wind.directionApparent', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1039, 4, 'environment.water.temperature', 'Water Temp', 'Pt', 'K', 8, 'environment.water.temperature', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1040, 4, 'environment.air.temperature', 'Air Temp', 'Pt', 'K', 8, 'environment.outside.temperature', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:19:18.213000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1041, 4, 'environment.outside.pressure', 'ENV Pressure', 'Pt', 'Pa', 8, 'environment.outside.pressure', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1042, 4, 'propulsion.main.revolutions', 'RPM', 'Pt', '', 8, 'propulsion.main.revolutions', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1043, 4, 'propulsion.port.engineTemperature', 'Eng Temp', 'Pt', 'K', 8, 'propulsion.main.temperature', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:21:59.237000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1044, 4, 'propulsion.main.oilPressure', 'Oil Press', 'Pt', '', 8, 'propulsion.main.oilPressure', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1045, 4, 'electrical.batteries.house.voltage', 'Batt Voltage', 'Pt', 'V', 8, 'electrical.dc.houseBattery.voltage', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:20:11.427000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1046, 4, 'electrical.batteries.house.current', 'Batt Current', 'Pt', 'A', 8, 'electrical.dc.houseBattery.current', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-22 20:19:55.207000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1047, 4, 'tanks.fuelTank.level', 'Fuel', 'Pt', '', 8, 'tanks.fuelTank.level', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1048, 4, 'tanks.freshWaterTank.level', 'Fresh Water', 'Pt', '', 8, 'tanks.freshWaterTank.level', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1049, 4, 'tanks.wasteWaterTank.level', 'Waste Water', 'Pt', '', 8, 'tanks.wasteWaterTank.level', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1050, 4, 'environment.water.seawater.pressure', 'Water Press', 'Pt', 'Pa', 8, 'environment.water.seawater.pressure', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1051, 4, 'environment.water.seawater.temperature', 'Seawater Temp', 'Pt', 'K', 8, 'environment.water.seawater.temperature', 'Y', CAST('2026-02-18 21:17:42.973000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1052, 5, 'navigation.position', 'Position', 'Pt', '', 8, 'navigation.position', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1053, 5, 'navigation.headingMagnetic', 'Hdg Mag', 'Pt', 'rad', 8, 'navigation.headingMagnetic', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1054, 5, 'navigation.headingTrue', 'Hdg True', 'Pt', 'rad', 8, 'navigation.headingTrue', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1055, 5, 'navigation.courseOverGround', 'COG', 'Pt', 'rad', 8, 'navigation.courseOverGround', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1056, 5, 'navigation.speedOverGround', 'SOG', 'Pt', 'm/s', 8, 'navigation.speedOverGround', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1057, 5, 'navigation.speedThroughWater', 'STW', 'Pt', '', 8, 'navigation.speedThroughWater', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1058, 5, 'environment.wind.speedApparent', 'Wind Speed', 'Pt', 'm/s', 8, 'environment.wind.speedApparent', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1059, 5, 'environment.wind.directionApparent', 'Wind Dir', 'Pt', 'rad', 8, 'environment.wind.directionApparent', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1060, 5, 'environment.water.temperature', 'Water Temp', 'Pt', 'K', 8, 'environment.water.temperature', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-22 21:41:14.377000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1061, 5, 'environment.outside.temperature', 'Air Temp', 'Pt', 'K', 8, 'environment.outside.temperature', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1062, 5, 'environment.outside.pressure', 'ENV Pressure', 'Pt', 'Pa', 8, 'environment.outside.pressure', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1063, 5, 'propulsion.main.revolutions', 'RPM', 'Pt', '', 8, 'propulsion.main.revolutions', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1064, 5, 'propulsion.main.temperature', 'Eng Temp', 'Pt', '', 8, 'propulsion.main.temperature', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1065, 5, 'propulsion.main.oilPressure', 'Oil Press', 'Pt', '', 8, 'propulsion.main.oilPressure', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1066, 5, 'electrical.dc.houseBattery.voltage', 'Batt Voltage', 'Pt', 'V', 8, 'electrical.dc.houseBattery.voltage', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1067, 5, 'electrical.dc.houseBattery.current', 'Batt Current', 'Pt', 'A', 8, 'electrical.dc.houseBattery.current', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1068, 5, 'tanks.fuelTank.level', 'Fuel', 'Pt', '', 8, 'tanks.fuelTank.level', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1069, 5, 'tanks.freshWaterTank.level', 'Fresh Water', 'Pt', '', 8, 'tanks.freshWaterTank.level', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1070, 5, 'tanks.wasteWaterTank.level', 'Waste Water', 'Pt', '', 8, 'tanks.wasteWaterTank.level', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1071, 5, 'environment.water.seawater.pressure', 'Water Press', 'Pt', 'Pa', 8, 'environment.water.seawater.pressure', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1072, 5, 'environment.water.seawater.temperature', 'Seawater Temp', 'Pt', 'K', 8, 'environment.water.seawater.temperature', 'Y', CAST('2026-02-18 21:17:42.983000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1073, 7, 'navigation.position', 'Position', 'Pt', '', 8, 'navigation.position', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1074, 7, 'navigation.headingMagnetic', 'Hdg Mag', 'Pt', 'rad', 8, 'navigation.headingMagnetic', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1075, 7, 'navigation.headingTrue', 'Hdg True', 'Pt', 'rad', 8, 'navigation.headingTrue', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1076, 7, 'navigation.courseOverGround', 'COG', 'Pt', 'rad', 8, 'navigation.courseOverGround', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1077, 7, 'navigation.speedOverGround', 'SOG', 'Pt', 'm/s', 8, 'navigation.speedOverGround', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1078, 7, 'navigation.speedThroughWater', 'STW', 'Pt', '', 8, 'navigation.speedThroughWater', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1079, 7, 'environment.wind.speedApparent', 'Wind Speed', 'Pt', 'm/s', 8, 'environment.wind.speedApparent', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1080, 7, 'environment.wind.directionApparent', 'Wind Dir', 'Pt', 'rad', 8, 'environment.wind.directionApparent', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1081, 7, 'environment.water.temperature', 'Water Temp', 'Pt', 'K', 8, 'environment.water.temperature', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-22 20:31:11.253000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1082, 7, 'environment.outside.temperature', 'Air Temp', 'Pt', 'K', 8, 'environment.outside.temperature', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1083, 7, 'environment.outside.pressure', 'ENV Pressure', 'Pt', 'Pa', 8, 'environment.outside.pressure', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1084, 7, 'propulsion.main.revolutions', 'RPM', 'Pt', '', 8, 'propulsion.main.revolutions', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1085, 7, 'propulsion.main.temperature', 'Eng Temp', 'Pt', '', 8, 'propulsion.main.temperature', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1086, 7, 'propulsion.main.oilPressure', 'Oil Press', 'Pt', '', 8, 'propulsion.main.oilPressure', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1087, 7, 'electrical.dc.houseBattery.voltage', 'Batt Voltage', 'Pt', 'V', 8, 'electrical.dc.houseBattery.voltage', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1088, 7, 'electrical.dc.houseBattery.current', 'Batt Current', 'Pt', 'A', 8, 'electrical.dc.houseBattery.current', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'Y');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1089, 7, 'tanks.fuelTank.level', 'Fuel', 'Pt', '', 8, 'tanks.fuelTank.level', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1090, 7, 'tanks.freshWaterTank.level', 'Fresh Water', 'Pt', '', 8, 'tanks.freshWaterTank.level', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1091, 7, 'tanks.wasteWaterTank.level', 'Waste Water', 'Pt', '', 8, 'tanks.wasteWaterTank.level', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1092, 7, 'environment.water.seawater.pressure', 'Water Press', 'Pt', 'Pa', 8, 'environment.water.seawater.pressure', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
INSERT INTO [EntityTypeAttribute] ([entityTypeAttributeId], [entityTypeId], [entityTypeAttributeCode], [entityTypeAttributeName], [entityTypeAttributeTimeAspect], [entityTypeAttributeUnit], [providerId], [providerEventType], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [protocolId], [defaultInGraph]) VALUES (1093, 7, 'environment.water.seawater.temperature', 'Seawater Temp', 'Pt', 'K', 8, 'environment.water.seawater.temperature', 'Y', CAST('2026-02-18 21:17:42.990000' AS DATETIME2), CAST('2026-02-23 09:24:25.137000' AS DATETIME2), 'sa', 3, 'N');
