-- Data for table: Event
-- Row count: 10

INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (1, 'NEWSTemperatureLowMedium', 'NEWS: Body temperature concern', 1, 3, 100, 'MEDIUM', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:45.987000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (2, 'NEWSSystolicBloodPressureLowMedium', 'NEWS: Systolic blood pressure concern', 1, 3, 100, 'MEDIUM', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:46.003000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (3, 'NEWSRespirationRatePerMinLowMedium', 'NEWS: Respiration rate (per min) concern', 1, 3, 100, 'MEDIUM', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:46.010000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (4, 'NEWSSpO2Scale1LowMedium', 'NEWS: SpO2 (scale 1) concern', 1, 3, 100, 'MEDIUM', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:46.013000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (5, 'NEWSPulsePerMinLowMedium', 'NEWS: Pulse rate (per min) concern', 1, 3, 100, 'MEDIUM', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:46.020000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (6, 'NEWSAggregateMedium', 'NEWS: Aggregation metrics medium alert', 1, 5, 6, 'MEDIUM', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:46.023000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (7, 'NEWSAggregateHigh', 'NEWS: Aggregation metrics high alert', 1, 7, 100, 'HIGH', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', CAST('2026-02-13 23:48:46.030000' AS DATETIME2), CAST('2026-02-14 15:16:28.910000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (8, 'RestHeartRateDrift', 'Rest: Heart Rate Drift', 1, 45, 100, 'HIGH', 2, 360, 7, 1.8, 4, '', NULL, 'BOTH', 'Y', CAST('2026-02-15 18:38:22.217000' AS DATETIME2), CAST('2026-02-15 23:10:56.143000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (9, 'HeartRateSpO2CorrelationShift', 'Multivariate: Heart Rate - SpO2 correlation shift detected', 1, 3, 100, 'MEDIUM', 3, 1440, 7, 0.25, 10, '{"expected_correlation": "negative", "description": "HR and SpO2 should maintain stable inverse correlation"}', NULL, NULL, 'Y', CAST('2026-02-15 23:52:55.877000' AS DATETIME2), CAST('2026-02-16 13:18:12.513000' AS DATETIME2), 'sa');
INSERT INTO [Event] ([eventId], [eventCode], [eventDescription], [entityTypeId], [minCumulatedScore], [maxCumulatedScore], [risk], [AnalyzeFunctionId], [LookbackMinutes], [BaselineDays], [SensitivityThreshold], [MinSamplesRequired], [CustomParams], [AggregationType], [AnomalyDirection], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser]) VALUES (10, 'GEOFENCE_BREACH', 'Insert into Restricted Area 1', 5, 0, 100, 'HIGH', 4, 0, 0, 0.0, 0, '', NULL, NULL, 'Y', CAST('2026-02-23 19:49:03.257000' AS DATETIME2), CAST('2026-02-23 20:01:47.420000' AS DATETIME2), 'sa');
