-- Data for table: Provider
-- Row count: 8

INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (1, 'Junction', 'Healthcare data integration platform', 'HealthData', 'https://api.junction.com', 'v1', 'https://docs.junction.com/events', 'Y', CAST('2026-02-07 18:49:33.920000' AS DATETIME2), CAST('2026-02-18 19:59:43.750000' AS DATETIME2), 'sa', 'junction-events', 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (2, 'Terra', 'Unified health data API platform', 'HealthData', 'https://api.terra.conduit.dev', 'v2', 'https://docs.terra.conduit.dev/reference/events', 'Y', CAST('2026-02-07 18:49:33.927000' AS DATETIME2), CAST('2026-02-18 19:59:43.753000' AS DATETIME2), 'sa', 'terra-health-vitals', 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (3, 'Apple', 'Apple Health platform', 'Wearable', NULL, NULL, 'https://developer.apple.com/health/', 'N', CAST('2026-02-07 18:49:33.930000' AS DATETIME2), CAST('2026-03-11 19:42:41.353000' AS DATETIME2), 'sa', NULL, 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (4, 'Garmin', 'Garmin wearable devices', 'Wearable', NULL, NULL, 'https://developer.garmin.com/health-api/overview/', 'N', CAST('2026-02-07 18:49:33.930000' AS DATETIME2), CAST('2026-03-11 19:42:54.307000' AS DATETIME2), 'sa', NULL, 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (5, 'SamsungHealth', 'Samsung Health SDK via VXT Mobile Gateway (device SW5) — IoT Hub native MQTT, LOINC-coded vitals', 'HealthData', NULL, '1.0', 'https://developer.samsung.com/health', 'Y', CAST('2026-02-07 18:49:33.933000' AS DATETIME2), CAST('2026-04-02 00:00:00.000000' AS DATETIME2), 'sa', 'samsung-health-vitals', 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (6, 'Fitbit', 'Fitbit health tracking', 'Wearable', NULL, NULL, 'https://dev.fitbit.com/docs/', 'N', CAST('2026-02-07 18:49:33.933000' AS DATETIME2), CAST('2026-03-11 19:42:47.590000' AS DATETIME2), 'sa', NULL, 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (7, 'GoogleFit', 'Google Fit fitness platform', 'Wearable', NULL, NULL, 'https://developers.google.com/fit', 'N', CAST('2026-02-07 18:49:33.937000' AS DATETIME2), CAST('2026-03-11 19:43:03.187000' AS DATETIME2), 'sa', NULL, 50);
INSERT INTO [Provider] ([providerId], [providerName], [providerDescription], [providerCategory], [apiBaseUrl], [apiVersion], [documentationUrl], [active], [createDate], [lastUpdateTimestamp], [lastUpdateUser], [TopicName], [BatchSize]) VALUES (8, 'N2KToSignalK', 'Signal K is an open-source data format for storing and sharing marine data. Converts NMEA 0183 and NMEA 2000 to standardized JSON format.', 'MaritimeData', 'https://signalk.org', 'v1.0', 'https://signalk.org/specification/latest/index.html', 'Y', CAST('2026-02-18 20:46:41.790000' AS DATETIME2), CAST('2026-02-18 20:46:41.790000' AS DATETIME2), 'sa', 'signalk-events', 100);
